### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by naitik2608** [INFO-526-S24/project-final-GraphGeeks#4]
The following is the peer review of the project proposal by Data Dazzlers. The team members that participated in this review are

- Varun Sahdev - @solitudevedhas
- Sanja Dmitrovic - @sdmitrovic
- Naitik Shah - @naitik2608
- Mohammad Farmani - @mfarmani95
- Jiayue - @Melissajiayue
- Vidhyananth - @Vidhyananth Sivashanmugam

- Describe the goal of the project.
The goal of the project, as understood from the proposal, is to analyze COVID-19 trends and the impacts of vaccination efforts globally and specifically within the USA, using advanced data visualization techniques. The project aims to reveal key patterns, insights, and correlations between different pandemic metrics (like case counts, recovery rates, and mortality) to provide actionable insights for policymakers and the public.
 
 
- Describe the data used or collected.
The project leverages comprehensive COVID-19 datasets from Kaggle, including day-wise global statistics, country-wise latest data, and detailed vaccination data. These datasets include metrics such as case counts, deaths, recoveries, vaccination figures, and more, which are critical for conducting a nuanced analysis of the pandemic's multifaceted impacts and trends.
 
- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The research questions focus on understanding the global trend of the COVID-19 pandemic over time and the relationship between vaccination efforts and the reduction in active cases. The team plans to use time-series plots, correlation coefficients, rolling average analyses, and anomaly detection, among other methods. They intend to employ R for analysis and the shiny package for creating interactive visualizations.
 
 
- Is there anything that is unclear from the proposal?
The question 1 was not clear enough to find what problem are you working on. For the first question analysis the rolling average would squeeze the data and only show averaged data which won’t reflect too much in the plots so using the daily data would show the real change in the number and the plot would be easy to understand. 

For the question 2 the question says they want to show the plots across different countries and in the analysis plan they talk about the counties column so you are focusing on USA or for the whole world was not clear

- Provide constructive feedback on how the team might be able to improve their project.
The proposal could benefit from a more detailed discussion on how the team will handle missing or incomplete data, as well as any potential biases within the datasets.
 Ethical considerations, especially regarding data privacy and the handling of sensitive health information, should be explicitly addressed.
 
 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are excited to see the Shiny app which would cover the interactive plots for the number of covid patients increasing over the time and along with that the patients recovering. This would be intersting to see in the World Map.
 
- Provide constructive feedback on any issues with file and/or code organization.

The Github url on the Website is not working. There was a spelling mistake of vaccine (*vaccian).
In the Timeline part the last row was not included in it and it looked like a text instead of a table.
 
- (Optional) Any further comments or feedback?
We are excited to see the shiny app which would be interactive. Also the findings for the new variants would be interesting. Also from where it started and the clustering the hotspots would be great.
All the Best!

**Comment by vemuladevendran** [comment]
## Response to Review Feedback

We appreciate the thorough review and valuable feedback provided. We have taken the following actions to address the points raised:

- We have rectified the issues identified in our proposal and made the necessary changes for clarity and precision.
- Spelling mistakes in the "Plan of Action" have been corrected, ensuring better readability and professionalism.
- For Question 2, we have clarified in our proposal that we will be using `usa_county_wise_data` for a more focused analysis within the United States, rather than a broader global perspective. Thank you for highlighting the need for this clarification.
- Regarding the GitHub URL issue, we have verified from our end that the link is functioning correctly. The problem might be specific to the settings or access permissions on the reviewer's side.
- The alignment issue in the timeline section was identified as a syntax error. We have corrected this, and the table now displays correctly in the proposal.

### Addressing Specific Feedback on Questions

- **Question 1 Clarification:** We've updated our proposal to specify that our analysis will utilize daily data alongside the rolling average. This approach allows us to observe immediate trends while also understanding longer-term patterns, ensuring a comprehensive view of the pandemic's progression.

- **Geographic Scope for Question 2:** We've explicitly stated that our analysis will concentrate on the USA, utilizing county-level data to provide detailed insights into the pandemic's impact and the vaccination efforts within the country.

We believe these adjustments have strengthened our proposal, ensuring that our research objectives are clear and our methodologies are well-defined. Thank you once again for the constructive feedback, which has been instrumental in refining our project approach.
